stages:
    - build
    - ani_deploy

build:
    image: harbor.yy.com/front_end/yyl:latest
    stage: build
    tags:
        - webfe
    artifacts:
        expire_in: 1 week
        paths:
            - output/
            - gitlog
    script:
        - mkdir output
        - yyl all --isCommit --name pc --logLevel 2 --mode $CI_COMMIT_REF_NAME
        - projectName=$(ls ./dist/project/)
        - cp --verbose -rf ./dist/project/$projectName/* ./output/
        - yyl all --isCommit --name mobile --logLevel 2 --mode $CI_COMMIT_REF_NAME
        - cp --verbose -rf ./dist/project/$projectName/* ./output/
        - rm --verbose -rf ./dist 

    after_script:
        - git log -1 --pretty=medium >> gitlog
    except:
        - schedules
    only:
        - /^(master|dev)$/

ani_deploy:
    image: harbor.yy.com/front_end/yyt:latest
    stage: ani_deploy
    retry: 2
    tags:
        - webfe
    artifacts:
        expire_in: 1 week
        paths:
            - output/
            - gitlog
    script:
        - yyt

    only:
        - schedules


